id: scenario_x
mission:
  id: mission_x
  type: parallel 
  # tasks:
  allocation: 
    - robot: tiago1
      pkg: floorplan-dsl-environments
      file_path: tasks/brsu_building_c_with_doors/right_long_corridor_task.yaml
    - robot: tiago2
      pkg: floorplan-dsl-environments
      file_path: tasks/brsu_building_c_with_doors/classroom_c069_task.yaml
    - robot: pmb1
      pkg: floorplan-dsl-environments
      file_path: tasks/brsu_building_c_with_doors/left_long_corridor_task.yaml
    - robot: omni1
      pkg: floorplan-dsl-environments
      file_path: tasks/brsu_building_c_with_doors/classroom_c018_task.yaml
environment:
  id: brsu_building_c_with_doors
  models:
    map: 
      map_name: brsu_building_c_with_doors
      pkg: floorplan-dsl-environments
      relative_path: maps/
    gazebo_world: 
      model_name: brsu_building_c_with_doors
      pkg: floorplan-dsl-environments
      relative_path: worlds/
  robots:
    tiago1:
      start_pose: 
        id: classroom_c069-w001
        x: 11.721145629882812
        y: 53.50111770629883
        z: 0.0
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
    tiago2:
      start_pose: 
        id: classroom_c069-w002
        x: 12.687057495117188
        y: 55.12968444824219
        z: 0.0
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
    pmb1:
      start_pose: 
        id: classroom_c025-w001
        x: 44.80387496948242
        y: 37.15502166748047
        z: 0.0
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
    omni1:
      start_pose: 
        id: classroom_c025-w002
        x: 43.432926177978516
        y: 38.493873596191406
        z: 0.0
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
robots:
  - robot_id: tiago1
    robot_namespace: tiago1
    robot_type: tiago
    configuration:
      hardware:
        base_type: pmb2
  - robot_id: tiago2
    robot_namespace: tiago2
    robot_type: tiago
    configuration:
      hardware:
        base_type: omni_base
  - robot_id: pmb1
    robot_namespace: pmb1
    robot_type: pmb2
    configuration:
      hardware:
        base_type: pmb2
  - robot_id: omni1
    robot_namespace: omni1
    robot_type: omni_base
    configuration:
      hardware:
        base_type: omni_base
